name: "Prepare nix-shell"
description:
  Download cache, build nix-shell and potentially upload any new
  derivations to cache

inputs:
  auth_token:
    required: true
  cache:
    default: niteo
  nix_path:
    default: nixpkgs=./nix/default.nix
  push_filter:
    default: 
    
runs:
  using: "composite"
  steps:

    - name: namespacelabs/nscloud-cache-action cannot mkdir /nix so we do it manually
      if: ${{ env.NSC_PROFILE_TAG }} != ''
      shell: bash
      run: |
        sudo mkdir /nix
        sudo chown $USER /nix

    - uses: namespacelabs/nscloud-cache-action@v1
      if: ${{ env.NSC_PROFILE_TAG }} != ''
      with:
        path: /nix

    - uses: cachix/install-nix-action@v22
      with:
        nix_path: ${{ inputs.nix_path }}
        
    - uses: cachix/cachix-action@v12
      with:
        name: ${{ inputs.cache }}
        authToken: ${{ inputs.auth_token }}
        pushFilter: ${{ inputs.push_filter }}

    - name: Build nix-shell
      shell: bash
      run: nix-shell --run "echo 'nix-shell successfully entered'"
