name: "Prepare nix-shell"
description:
  Download cache, build nix-shell and potentially upload any new
  derivations to cache

inputs:
  auth_token:
    required: true
  cache:
    default: niteo
  nix_path:
    default: nixpkgs=./nix/default.nix
  pushFilter:
    default: ""
  
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: ${{ inputs.nix_path }}
        
    - uses: cachix/cachix-action@v12
      with:
        name: ${{ inputs.cache }}
        authToken: ${{ inputs.auth_token }}
        pushFilter: ${{ inputs.pushFilter }}

    - name: Build nix-shell
      shell: bash
      run: nix-shell --run "echo 'nix-shell successfully entered'"
